// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsvXQk_GGK_ctgRhMPbhs-sJKtdL3uopk',
    appId: '1:899258735602:web:8a719b9a39aa797704e96b',
    messagingSenderId: '899258735602',
    projectId: 'lovecost-93318',
    authDomain: 'lovecost-93318.firebaseapp.com',
    storageBucket: 'lovecost-93318.firebasestorage.app',
    measurementId: 'G-YWBT8NEY75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFDtx2pglZhkX4SV33w8cP0uNaxNk57Cs',
    appId: '1:899258735602:android:3973455f10833b9504e96b',
    messagingSenderId: '899258735602',
    projectId: 'lovecost-93318',
    storageBucket: 'lovecost-93318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjOIwZJv3A9yebwknkqxAVIKHLbBp-C6I',
    appId: '1:899258735602:ios:e6293eece39c891804e96b',
    messagingSenderId: '899258735602',
    projectId: 'lovecost-93318',
    storageBucket: 'lovecost-93318.firebasestorage.app',
    iosBundleId: 'com.example.lovecost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjOIwZJv3A9yebwknkqxAVIKHLbBp-C6I',
    appId: '1:899258735602:ios:e6293eece39c891804e96b',
    messagingSenderId: '899258735602',
    projectId: 'lovecost-93318',
    storageBucket: 'lovecost-93318.firebasestorage.app',
    iosBundleId: 'com.example.lovecost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsvXQk_GGK_ctgRhMPbhs-sJKtdL3uopk',
    appId: '1:899258735602:web:b00752ae630ac8b804e96b',
    messagingSenderId: '899258735602',
    projectId: 'lovecost-93318',
    authDomain: 'lovecost-93318.firebaseapp.com',
    storageBucket: 'lovecost-93318.firebasestorage.app',
    measurementId: 'G-YJ7EX7X4PE',
  );
}
